name: Build gxvm/gxasm
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup build environment
        run: |
          sudo apt update
          sudo apt install mingw-w64
          ./setup.sh
          TARGET=Windows_NT ./setup.sh
          
      - name: Build gxvm
        run: |
          ./build.sh
          TARGET=Windows_NT ./build.sh
          
      - name: Build gxasm
        run: |
          ./build_asm.sh
          TARGET=Windows_NT ./build_asm.sh

      - uses: actions/upload-artifact@v3.0.0
        with:
          name: gxarch-linux
          path: |
            gxvm
            gxasm
            
      - uses: actions/upload-artifact@v3.0.0
        with:
          name: gxarch-windows
          path: |
            gxvm.exe
            gxasm.exe
